# Generated by Django 5.2 on 2025-05-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_alter_rol_descripcion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permiso_rol',
            unique_together={('rol_id', 'permiso_id')},
        ),
    ]
