# Generated by Django 5.2 on 2025-05-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_insumo_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='cantidad',
            new_name='stock',
        ),
    ]
